# Site settings
title: Edinburgh Brewing Cooperative
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Edinburgh Brewing Cooperative is starting up, check here
  for recipes and information about us.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://edinburgh-brewing-coop.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  edinburgh-brewing-coop

# Build settings
markdown: kramdown

paginate: 4

author: Edinburgh Brewing Cooperative

gems: [jekyll-paginate]
